export const svgs = {
  analytic: '/assets/svgs/analytic.svg',
  dashBoard: '/assets/svgs/dashboard.svg',
  planWeek: '/assets/svgs/planWeek.svg',
  peopleManage: '/assets/svgs/peopleManage.svg',
  lectureManage: '/assets/svgs/lectureManage.svg',
  manageGoCome: '/assets/svgs/manageGoCome.svg',
  report: '/assets/svgs/report.svg',
  plus: '/assets/svgs/plus.svg',
  trash: '/assets/svgs/trash.svg',
  vector: '/assets/svgs/vector.svg',
  eyeOpen: '/assets/svgs/eyeOpen.svg',
  warning: '/assets/svgs/warning.svg',
  clockCircle: '/assets/svgs/ClockCircle.svg',
  exportFile: '/assets/svgs/Upload.svg',
  search: '/assets/svgs/search.svg',
  closeIcon: '/assets/svgs/closeIcon.svg',
  iconActive: '/assets/svgs/iconActive.svg',
  iconPlay: '/assets/svgs/iconPlay.svg',
  iconArrowUp: '/assets/svgs/icArrowUp.svg',
  iconArrowDown: '/assets/svgs/iconArrowDown.svg',
  iconRing: '/assets/svgs/iconRing.svg',
  DotThree: '/assets/svgs/DotThree.svg',
  arrUpWhite: '/assets/svgs/arrUpWhite.svg',
  menuTab: "/assets/svgs/menuTab.svg",
  closeMenu: "/assets/svgs/closeMenu.svg",
  GroupMenu: "/assets/svgs/GroupMenu.svg",
};
