"use client"

import { Footer } from "@/components/Common/Footer"
import { Header } from "@/components/Common/Header"
import MenuHeader from "@/components/Common/MenuHeader"
import {
    Breadcrumb,
    BreadcrumbItem,
    BreadcrumbLink,
    BreadcrumbList,
    BreadcrumbSeparator,
} from "@/components/ui/breadcrumb"
import Image from "next/image"

export default function SupportPolicyPage() {
    return (
        <div className="min-h-screen bg-background flex flex-col">
            <Header/>
            <MenuHeader />
            <section className="w-full py-8 px-[104px] bg-[#E3E6E6]">
                <div className="flex items-center justify-between">
                    <h1 className="text-2xl font-bold">Trang chính sách hỗ trợ</h1>
                    <Breadcrumb>
                        <BreadcrumbList>
                            <BreadcrumbItem>
                                <BreadcrumbLink href="/">
                                    Trang chủ
                                </BreadcrumbLink>
                            </BreadcrumbItem>
                            <BreadcrumbSeparator />
                            <BreadcrumbItem>
                                <BreadcrumbLink 
                                    className="font-semibold" 
                                    href="/support-policy" 
                                >
                                    Trang chính sách hỗ trợ
                                </BreadcrumbLink>
                            </BreadcrumbItem>
                        </BreadcrumbList>
                    </Breadcrumb>
                </div>
            </section>
            <section className="w-full pb-4 px-[104px] bg-[#E3E6E6]">
                <div className="p-4 bg-white rounded shadow-sm overflow-hidden text-left">
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            Thank you for shopping at{' '}
                            <Image
                                draggable={false}
                                src="https://img5.yeshen.cc/vn-alibaba/28/0a/28f8e540a990fac2f6dcdec0d4a0160df3f8cb0a.jpg"
                                alt="Logo"
                                width={44}
                                height={16}
                                style={{ display: 'inline-block', position: 'relative', bottom: '1px' }}
                            />
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            If, for any reason, You are not completely satisfied with a purchase We invite You to review our policy on refunds and returns. This Return and Refund Policy was generated by TermsFeed Return and Refund Policy Generator.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The following terms are applicable for any products that You purchased with Us.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            Interpretation and Definitions
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            Interpretation
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            Definitions
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            For the purposes of this Return and Refund Policy:
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            "Company" (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to{' '}
                            <Image
                                draggable={false}
                                src="https://img5.yeshen.cc/vn-alibaba/28/0a/28f8e540a990fac2f6dcdec0d4a0160df3f8cb0a.jpg"
                                alt="Logo"
                                width={44}
                                height={16}
                                style={{ display: 'inline-block', position: 'relative', bottom: '1px' }}
                            />
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            "Goods" refers to the items offered for sale on the Service.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            "Orders" means a request by You to purchase Goods from Us.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            "Service" refers to the Website.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            "Website" refers to{' '}
                            <Image
                                draggable={false}
                                src="https://img5.yeshen.cc/vn-alibaba/28/0a/28f8e540a990fac2f6dcdec0d4a0160df3f8cb0a.jpg"
                                alt="Logo"
                                width={44}
                                height={16}
                                style={{ display: 'inline-block', position: 'relative', bottom: '1px' }}
                            />, accessible from amazonPro.com
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            "You" means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            Your Order Cancellation Rights
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            You are entitled to cancel Your Order within 14 days without giving any reason for doing so.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The deadline for cancelling an Order is 14 days from the date on which You received the Goods or on which a third party you have appointed, who is not the carrier, takes possession of the product delivered.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            In order to exercise Your right of cancellation, You must inform Us of your decision by means of a clear statement. You can inform us of your decision by:
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            By sending us an email: amazon66@gmail.com
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            We will reimburse You no later than 14 days from the day on which We receive the returned Goods. We will use the same means of payment as You used for the Order, and You will not incur any fees for such reimbursement.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            Conditions for Returns
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            In order for the Goods to be eligible for a return, please make sure that:
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The Goods were purchased in the last 14 days
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The Goods are in the original packaging
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The following Goods cannot be returned:
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The supply of Goods made to Your specifications or clearly personalized.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The supply of Goods which according to their nature are not suitable to be returned, deteriorate rapidly or where the date of expiry is over.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The supply of Goods which are not suitable for return due to health protection or hygiene reasons and were unsealed after delivery.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            The supply of Goods which are, after delivery, according to their nature, inseparably mixed with other items.
                        </span>
                    </div>
                    <div>
                        <span style={{ color: '#1b1b28', caretColor: 'rgb(27, 27, 40)' }}>
                            We reserve the right to refuse returns of any merchandise that does not meet the above return conditions in our sole discretion.
                        </span>
                    </div>
                </div>
            </section>
            <Footer />
        </div>
    )
}

